export const LOGIN_REQUEST  = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS= 'USERS_LOGIN_SUCCESS';
export const LOGIN_ERROR = 'USERS_LOGIN_ERROR';
export const LOGOUT = 'USERS_LOGOUT';
export const FETCH_LOGGED_IN_USER = 'FETCH_LOGGED_IN_USER';
export const FETCH_LOGGED_IN_USER_SUCCESS = 'FETCH_LOGGED_IN_USER_SUCCESS';
export const FETCH_LOGGED_IN_USER_ERROR = 'FETCH_LOGGED_IN_USER_ERROR';
